SELECT SYS.TABLES.NAME AS TABLA, ALL_COLUMNS.NAME AS COLUMNA, user_type_id, SYS.DEFAULT_CONSTRAINTS.NAME AS CAMPODEFAULT
FROM SYS.ALL_COLUMNS 
	INNER JOIN SYS.TABLES ON ALL_COLUMNS.OBJECT_ID = TABLES.OBJECT_ID AND NOT SYS.TABLES.NAME LIKE 'tmp%' AND SYS.TABLES.NAME <> 'tCTLrecursosTemporales'
	INNER JOIN SYS.SCHEMAS ON TABLES.SCHEMA_ID = SCHEMAS.SCHEMA_ID AND IS_IDENTITY = 0 AND SYS.ALL_COLUMNS.IS_COMPUTED = 0 AND SYS.ALL_COLUMNS.COLUMN_ID <> 1 AND USER_TYPE_ID <> 165
	LEFT JOIN SYS.DEFAULT_CONSTRAINTS ON ALL_COLUMNS.DEFAULT_OBJECT_ID = DEFAULT_CONSTRAINTS.OBJECT_ID 
WHERE SYS.DEFAULT_CONSTRAINTS.NAME IS NULL AND NOT SYS.TABLES.NAME IN('tCTLpermisosBorrados','tCTLconsultas201408030216','tempTCTLdominiosOperaciones','sysdiagrams')



