SELECT TBL.NAME, SUM(PART.ROWS) AS ROWS
FROM SYS.TABLES TBL
INNER JOIN SYS.PARTITIONS PART ON TBL.OBJECT_ID = PART.OBJECT_ID AND NOT NAME LIKE 'tmp%'
GROUP BY TBL.OBJECT_ID, TBL.NAME
--HAVING SUM(PART.ROWS) = 0
ORDER BY ROWS, NAME;


