

SELECT SC.NAME +'.'+ TA.NAME AS TABLA, SUM(PA.ROWS) AS REGISTROS
FROM SYS.TABLES TA 
	INNER JOIN SYS.PARTITIONS PA ON PA.OBJECT_ID  = TA.OBJECT_ID 
	INNER JOIN SYS.SCHEMAS SC ON TA.SCHEMA_ID = SC.SCHEMA_ID 
WHERE  TA.IS_MS_SHIPPED = 0 
		AND PA.INDEX_ID IN (1, 0) 		
GROUP  BY SC.NAME, TA.NAME 
--HAVING SUM(PA.ROWS) > 1
ORDER BY  SUM(PA.ROWS) DESC, TA.NAME		


