DECLARE @TABLA AS VARCHAR(100)	=	'tSCSemisoresProveedores'
declare @CAMPO AS VARCHAR(100)	=	'IdTipoDproveedorInstitucional'

DECLARE	@sql AS VARCHAR(MAX)	=	(SELECT 'IF EXISTS(SELECT * FROM SYS.DEFAULT_CONSTRAINTS WHERE PARENT_OBJECT_ID = OBJECT_ID('''+@TABLA+''') AND NAME = '''+name+''') '+CHAR(13)+'ALTER TABLE '+@TABLA+' DROP CONSTRAINT '+ name +' '
									FROM SYS.DEFAULT_CONSTRAINTS 
									WHERE PARENT_OBJECT_ID = OBJECT_ID(''+@TABLA+'') AND COL_NAME(parent_object_id,parent_column_id) = @CAMPO)

DECLARE @query AS VARCHAR(MAX)	=	(SELECT 'IF EXISTS(SELECT * FROM SYS.FOREIGN_KEYS WHERE PARENT_OBJECT_ID = OBJECT_ID('''+@TABLA+''') AND NAME = '''+fk.name+''') '+CHAR(13)+'ALTER TABLE '+@TABLA+' DROP CONSTRAINT '+ fk.name +' '		
									FROM SYS.FOREIGN_KEYS fk INNER JOIN SYS.FOREIGN_KEY_COLUMNS fkc ON fk.OBJECT_ID = fkc.CONSTRAINT_OBJECT_ID 
									WHERE FK.PARENT_OBJECT_ID = OBJECT_ID(@TABLA) AND COL_NAME(FK.PARENT_OBJECT_ID, PARENT_COLUMN_ID) = @CAMPO)

EXECUTE (@sql)
EXECUTE (@query)


IF EXISTS(SELECT * FROM SYS.COLUMNS WHERE OBJECT_ID = OBJECT_ID(@Tabla) AND NAME = @CAMPO)
EXECUTE ('ALTER TABLE '+@Tabla+' DROP COLUMN '+@Campo+' ')
GO
