

IF EXISTS (SELECT 1
           FROM ##NOMINA PercepcionDeduccion
           LEFT JOIN dbo.vPERempleados e ON PercepcionDeduccion.concepto = e.Codigo
           WHERE ISNULL (TRY_CAST(PercepcionDeduccion.CONCEPTO AS INT), 0) <> 0 AND e.IdEmpleado IS NULL)
BEGIN
    SELECT PercepcionDeduccion.EMPLEADO,
           PercepcionDeduccion.CONCEPTO,
           PercepcionDeduccion.NOMBRE,
           PercepcionDeduccion.PERCEPCIONES,
           INFO = 'Este numero de empleado no existe en ERPRISE.'
    FROM ##NOMINA PercepcionDeduccion
    LEFT JOIN dbo.vPERempleados e ON PercepcionDeduccion.concepto = e.Codigo
    WHERE ISNULL (TRY_CAST(PercepcionDeduccion.CONCEPTO AS INT), 0) <> 0 AND e.IdEmpleado IS NULL;

    RETURN;
END;

UPDATE PercepcionDeduccion
SET EMPLEADO = PercepcionDeduccion.CONCEPTO
FROM ##NOMINA PercepcionDeduccion
INNER JOIN dbo.vPERempleados e ON PercepcionDeduccion.concepto = e.Codigo
WHERE ISNULL (TRY_CAST(PercepcionDeduccion.CONCEPTO AS INT), 0) <> 0;

DELETE PercepcionDeduccion
FROM ##NOMINA PercepcionDeduccion
WHERE EMPLEADO IS NULL AND PATINDEX ('%[^PD0-9]%', CONCEPTO) <> 0;

DELETE FROM ##NOMINA
WHERE CONCEPTO IS NULL AND EMPLEADO IS NULL AND NOMBRE IS NULL AND PERCEPCIONES IS NULL AND [PERC# GRAVADA] IS NULL AND [PERC# EXENTA] IS NULL AND [PERC# OTROS] IS NULL AND DEDUCCIONES IS NULL AND OBLIGACIONES IS NULL;

DELETE FROM ##NOMINA
WHERE EMPLEADO IS NULL AND CONCEPTO IS NULL AND NOMBRE IS NULL;

UPDATE PercepcionDeduccion
SET NOMBRE = PERCEPCIONES
FROM ##NOMINA PercepcionDeduccion
WHERE EMPLEADO IS NOT NULL;

UPDATE PercepcionDeduccion
SET PERCEPCIONES = 0
FROM ##NOMINA PercepcionDeduccion
WHERE EMPLEADO IS NOT NULL;

UPDATE PercepcionDeduccion
SET PERCEPCIONES = REPLACE (PERCEPCIONES, ',', ''),
    [PERC# GRAVADA] = REPLACE ([PERC# GRAVADA], ',', ''),
    [PERC# EXENTA] = REPLACE ([PERC# EXENTA], ',', ''),
    [PERC# OTROS] = REPLACE ([PERC# OTROS], ',', ''),
    DEDUCCIONES = REPLACE (DEDUCCIONES, ',', '')
FROM ##NOMINA PercepcionDeduccion;



ALTER TABLE ##NOMINA ALTER COLUMN PERCEPCIONES DECIMAL(18, 2);
ALTER TABLE ##NOMINA ALTER COLUMN [PERC# GRAVADA] DECIMAL(18, 2);
ALTER TABLE ##NOMINA ALTER COLUMN [PERC# EXENTA] DECIMAL(18, 2);
ALTER TABLE ##NOMINA ALTER COLUMN [PERC# OTROS] DECIMAL(18, 2);
ALTER TABLE ##NOMINA ALTER COLUMN DEDUCCIONES DECIMAL(18, 2);
ALTER TABLE ##NOMINA ALTER COLUMN OBLIGACIONES DECIMAL(18, 2);

DELETE FROM ##NOMINA
WHERE CONCEPTO IS NULL AND (ISNULL ([PERC# GRAVADA], 0) + ISNULL ([DEDUCCIONES], 0)) > 0;

DELETE FROM ##NOMINA
WHERE CONCEPTO IS NULL;

SELECT EMPLEADO = ISNULL (EMPLEADO, ''),
       CONCEPTO = COALESCE (CONCEPTO, ''),
       F3 = COALESCE (NOMBRE, ''),
       PERCEPCIONES = ISNULL (PERCEPCIONES, 0),
       [PERC# GRAVADA] = ISNULL ([PERC# GRAVADA], 0),
       [PERC# EXENTA] = ISNULL ([PERC# EXENTA], 0),
       [PERC# OTROS] = ISNULL ([PERC# OTROS], 0),
       DEDUCCIONES = ISNULL (DEDUCCIONES, 0),
       OBLIGACIONES = ISNULL (OBLIGACIONES, 0),
       PERIODO = ISNULL (PERIODO, '')
FROM ##NOMINA PercepcionDeduccion;
