
SELECT ' '''+documento+''', ' 
FROM tblArchivos WITH (NOLOCK)
--WHERE documento NOT IN ('CURP', 'INGESO', 'ACABEN', 'CURSOL', 'IFTSOL', 'CURBEN', 'INGRES', 'CORQUIS','CRUPBEN','IMGRESO','CRUPSOL','0','1','IFESOL1','FOTOSOL','CROQIUS','CUPRBEN','DOICILIO','ACTABEN0','IFESOL30','CCROQUIS','CURPSOL0','DIMICILIO','INGRESO,0','ACTABEN,0','DOMICILIOM','ACTASOL,0}')
GROUP BY documento
ORDER BY LEN(documento)

SELECT *
FROM tblArchivos
WHERE documento IN (

			SELECT documento
			FROM tblArchivos WITH (NOLOCK)
			WHERE documento NOT IN ('CURP', 'INGESO', 'ACABEN', 'CURSOL', 'IFTSOL', 'CURBEN', 'INGRES', 'CORQUIS','CRUPBEN','IMGRESO','CRUPSOL','0','1','IFESOL1','FOTOSOL','CROQIUS','CUPRBEN','DOICILIO','ACTABEN0','IFESOL30','CCROQUIS','CURPSOL0','DIMICILIO','INGRESO,0','ACTABEN,0','DOMICILIOM','ACTASOL,0}')
			GROUP BY documento			
)

select * from tblArchivos where documento = 'FOTO'


SELECT Nombre, Fecha, pathFile
FROM tblArchivos
WHERE documento IN ('FOTO','IFESOL','IFEBEN','CROQUIS','ACTABEN','INGRESO','ACTASOL','CURPSOL','CURPBEN','DOMICILIO')